# Generated by Django 3.2.12 on 2022-02-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220225_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientcount',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='need_for_recipes',
            field=models.ManyToManyField(through='api.IngredientCount', to='api.Recipes'),
        ),
        migrations.AlterField(
            model_name='ingredientcount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='use_ingredient', to='api.ingredients'),
        ),
    ]
