# Generated by Django 3.2.12 on 2022-02-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220225_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='need_for_recipes',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient',
            field=models.ManyToManyField(related_name='use_ingredient', through='api.IngredientCount', to='api.Ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientcount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ingredients'),
        ),
    ]
