# Generated by Django 3.2.12 on 2022-03-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220308_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredientcount',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientcount',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='IngredientCount',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
